autographs_system_cleanup_deploy_path: /opt/autographs
autographs_system_cleanup_env_path: "{{ autographs_system_cleanup_deploy_path }}/env"
autographs_system_cleanup_controller_image_repository: ghcr.io/jetsaredim/autographs/controller
autographs_system_cleanup_retain_count: 3
autographs_system_cleanup_protected_tags: production
autographs_system_cleanup_dry_run: "false"
