import type { AutographItemInput } from "../../src/catalog/types";

export const sampleAutographs: AutographItemInput[] = [
  {
    title: "Signed baseball from spring training",
    signer: "Maya Thompson",
    description:
      "Baseball signed in blue ink after a spring training exhibition game.",
    category: "Sports",
    tags: ["baseball", "spring-training", "ball"],
    objectReference: "shelf-a/bin-01",
    eventName: "Spring Training",
    eventLocation: "Scottsdale, AZ",
    source: "In-person signing",
    inscription: "Best wishes",
    certificationCompany: "PSA",
    certificationId: "PSA-123456",
    estimatedYear: 2023,
    publicationStatus: "published",
    images: [
      {
        storageNamespace: "local-fixtures",
        bucketName: "autographs-media-dev",
        objectKey: "samples/maya-thompson/baseball-primary.svg",
        contentType: "image/svg+xml",
        byteSize: 512,
        checksum: "sample-maya-primary",
        etag: "sample-maya-primary",
        isPrimary: true,
        sortOrder: 0,
        altText: "Signed baseball primary view",
      },
      {
        storageNamespace: "local-fixtures",
        bucketName: "autographs-media-dev",
        objectKey: "samples/maya-thompson/baseball-cert.svg",
        contentType: "image/svg+xml",
        byteSize: 384,
        checksum: "sample-maya-cert",
        etag: "sample-maya-cert",
        isPrimary: false,
        sortOrder: 1,
        altText: "Certification label for signed baseball",
      },
    ],
  },
  {
    title: "Concert poster signed backstage",
    signer: "The Midnight Letters",
    description:
      "Tour poster signed by the full band after the encore meet-and-greet.",
    category: "Music",
    tags: ["poster", "concert", "band"],
    objectReference: "portfolio-02/page-04",
    eventName: "North Loop Tour",
    eventLocation: "Minneapolis, MN",
    source: "Meet-and-greet",
    inscription: "Thanks for listening",
    certificationCompany: null,
    certificationId: null,
    estimatedYear: 2022,
    publicationStatus: "published",
    images: [
      {
        storageNamespace: "local-fixtures",
        bucketName: "autographs-media-dev",
        objectKey: "samples/midnight-letters/poster-primary.svg",
        contentType: "image/svg+xml",
        byteSize: 640,
        checksum: "sample-midnight-primary",
        etag: "sample-midnight-primary",
        isPrimary: true,
        sortOrder: 0,
        altText: "Signed concert poster",
      },
    ],
  },
  {
    title: "Draft catalog entry for signed trading card",
    signer: "Jordan Ellis",
    description:
      "Draft record used to verify unpublished items stay out of public gallery flows.",
    category: "Trading Cards",
    tags: ["card", "draft", "verification"],
    objectReference: "binder-01/page-09",
    eventName: "Card Expo",
    eventLocation: "Cleveland, OH",
    source: "Dealer signing table",
    inscription: null,
    certificationCompany: "Beckett",
    certificationId: "BAS-78910",
    estimatedYear: 2021,
    publicationStatus: "draft",
    images: [
      {
        storageNamespace: "local-fixtures",
        bucketName: "autographs-media-dev",
        objectKey: "samples/jordan-ellis/card-primary.svg",
        contentType: "image/svg+xml",
        byteSize: 448,
        checksum: "sample-jordan-primary",
        etag: "sample-jordan-primary",
        isPrimary: true,
        sortOrder: 0,
        altText: "Signed trading card draft image",
      },
    ],
  },
];
