autographs_deploy_user: opc

autographs_deploy_deploy_path: /opt/autographs
autographs_deploy_env_path: "{{ autographs_deploy_deploy_path }}/env"
autographs_deploy_wallet_path: "{{ autographs_deploy_deploy_path }}/wallet"
autographs_deploy_secrets_path: "{{ autographs_deploy_deploy_path }}/secrets"
autographs_deploy_caddy_path: "{{ autographs_deploy_deploy_path }}/caddy"
autographs_deploy_static_path: "{{ autographs_deploy_deploy_path }}/static"
autographs_deploy_static_admin_path: "{{ autographs_deploy_deploy_path }}/static-admin"

autographs_deploy_quadlet_path: /etc/containers/systemd
autographs_deploy_network_name: autographs
autographs_deploy_controller_container_name: autographs-controller
autographs_deploy_caddy_container_name: autographs-caddy
autographs_deploy_static_vol_name: autographs-static
autographs_deploy_caddy_data_vol_name: autographs-caddy-data
autographs_deploy_caddy_config_vol_name: autographs-caddy-config
autographs_deploy_caddy_image: docker.io/library/caddy:2-alpine
autographs_deploy_http_port: 80
autographs_deploy_https_port: 443
autographs_deploy_candidate_preview_port: 8081
autographs_deploy_controller_port: 8080
autographs_deploy_domain: autographs.jetsaredim.net
autographs_deploy_controller_db_provider: "{{ lookup('env', 'AUTOGRAPHS_CONTROLLER_DB_PROVIDER') | default('oracle', true) }}"
autographs_deploy_controller_media_storage_provider: >-
  {{ lookup('env', 'AUTOGRAPHS_CONTROLLER_MEDIA_STORAGE_PROVIDER') | default('oci-instance-principal', true) }}
autographs_deploy_controller_local_media_root: >-
  {{ lookup('env', 'AUTOGRAPHS_CONTROLLER_LOCAL_MEDIA_ROOT') | default('/tmp/autographs-controller-media', true) }}

autographs_deploy_packages:
  - podman
  - firewalld
  - unzip
  - oraclelinux-developer-release-el10

autographs_deploy_operator_packages:
  - python3-oci-cli

autographs_deploy_operator_package_repos:
  - ol10_developer

autographs_deploy_masked_services:
  - oracle-cloud-agent.service
  - oracle-cloud-agent-updater.service
  - dnf-makecache.timer
  - fwupd-refresh.timer
  - pmie_check.timer
  - pmie_farm_check.timer
  - pmie_daily.timer
  - pmlogger_check.timer
  - pmlogger_farm_check.timer
  - pmlogger_daily.timer

autographs_deploy_swap_file: /.swapfile
autographs_deploy_swap_size_mib: 2048
autographs_deploy_swappiness: 20
