autographs_deploy_user: opc

autographs_deploy_deploy_path: /opt/autographs
autographs_deploy_env_path: "{{ autographs_deploy_deploy_path }}/env"
autographs_deploy_wallet_path: "{{ autographs_deploy_deploy_path }}/wallet"
autographs_deploy_secrets_path: "{{ autographs_deploy_deploy_path }}/secrets"
autographs_deploy_caddy_path: "{{ autographs_deploy_deploy_path }}/caddy"
autographs_deploy_caddy_data_path: "{{ autographs_deploy_deploy_path }}/caddy-data"
autographs_deploy_caddy_config_path: "{{ autographs_deploy_deploy_path }}/caddy-config"

autographs_deploy_quadlet_path: /etc/containers/systemd
autographs_deploy_network_name: autographs
autographs_deploy_app_container_name: autographs-app
autographs_deploy_caddy_container_name: autographs-caddy
autographs_deploy_caddy_image: docker.io/library/caddy:2-alpine
autographs_deploy_http_port: 80
autographs_deploy_https_port: 443
autographs_deploy_domain: autographs.jetsaredim.net

autographs_deploy_packages:
  - podman
  - firewalld
  - unzip

autographs_deploy_masked_services:
  - oracle-cloud-agent.service
  - oracle-cloud-agent-updater.service
  - dnf-makecache.timer
  - fwupd-refresh.timer
  - pmie_check.timer
  - pmie_farm_check.timer
  - pmie_daily.timer
  - pmlogger_check.timer
  - pmlogger_farm_check.timer
  - pmlogger_daily.timer

autographs_deploy_swap_file: /.swapfile
autographs_deploy_swap_size_mib: 2048
autographs_deploy_swappiness: 20
