import { createCatalogRepository } from "../src/catalog";
import { createCatalogService } from "../src/catalog";
import { createPrivateMediaStore } from "../src/media";
import type { MediaObjectLocation, MediaReadResult } from "../src/media";

const main = async (): Promise<void> => {
  const mediaStore = createPrivateMediaStore();
  await createCatalogRepository().list({ includeUnpublished: true });
  await mediaStore.assertReady();

  const service = createCatalogService();
  let itemId: string | null = null;
  let imageId: string | null = null;
  let mediaLocation: MediaObjectLocation | null = null;

  try {
    const fixture = Buffer.from(
      `<svg xmlns="http://www.w3.org/2000/svg" width="320" height="180"><rect width="320" height="180" fill="#f4f4f5"/><text x="24" y="96" font-family="Arial" font-size="24">Autographs smoke</text></svg>`,
    );
    const item = await service.create({
      title: `Smoke test autograph ${new Date().toISOString()}`,
      signer: "Phase Two Smoke",
      description: "Generated by the Phase 2 data/media smoke script.",
      category: "Verification",
      tags: ["smoke", "phase-2"],
      source: "Automated smoke script",
      publicationStatus: "published",
      imageUploads: [
        {
          filename: "smoke.svg",
          contentType: "image/svg+xml",
          body: fixture,
          byteSize: fixture.byteLength,
          isPrimary: true,
          sortOrder: 0,
          altText: "Generated smoke-test SVG",
        },
      ],
    });
    itemId = item.id;

    const [listed, readBack] = await Promise.all([
      service.list({ tag: "smoke" }),
      service.getById(item.id),
    ]);
    const primaryImage = readBack?.images.find((image) => image.isPrimary);

    if (!readBack || !primaryImage || !listed.some((candidate) => candidate.id === item.id)) {
      throw new Error("Smoke item could not be read back through the catalog service.");
    }
    imageId = primaryImage.id;

    const mediaRead = await service.readPublishedImage(item.id, primaryImage.id);
    if (!mediaRead) {
      throw new Error("Smoke image could not be read through the app-mediated service path.");
    }
    mediaLocation = {
      storageNamespace: mediaRead.storageNamespace,
      bucketName: mediaRead.bucketName,
      objectKey: mediaRead.objectKey,
    };

    const baseUrl = process.env.AUTOGRAPHS_SMOKE_BASE_URL;
    if (baseUrl) {
      const response = await fetch(
        `${baseUrl.replace(/\/$/, "")}/api/catalog/${item.id}/images/${primaryImage.id}`,
      );
      if (!response.ok) {
        throw new Error(`App-mediated smoke image route failed with ${response.status}.`);
      }
    }

    await createPrivateMediaStore().assertReady();
    console.log(
      JSON.stringify({
        ok: true,
        scope: "data-live",
        itemId: item.id,
        imageId: primaryImage.id,
        appRouteChecked: Boolean(baseUrl),
      }),
    );
  } finally {
    if (itemId) {
      const deleted = await service.delete(itemId);
      const readAfterDelete = await service.getById(itemId, { includeUnpublished: true });

      if (readAfterDelete) {
        throw new Error(`Smoke item ${itemId} still exists after cleanup.`);
      }
      if (mediaLocation) {
        await assertMediaObjectDeleted(mediaStore, mediaLocation);
      }

      console.log(
        JSON.stringify({
          ok: true,
          scope: "data-live-cleanup",
          itemId,
          imageId,
          deletedImageCount: deleted.images.length,
        }),
      );
    }
  }
};

const assertMediaObjectDeleted = async (
  mediaStore: ReturnType<typeof createPrivateMediaStore>,
  location: MediaObjectLocation,
): Promise<void> => {
  try {
    const result = await mediaStore.read(location);
    await drainBody(result.body);
  } catch {
    return;
  }

  throw new Error(`Smoke media object ${location.objectKey} still exists after cleanup.`);
};

const drainBody = async (body: MediaReadResult["body"]): Promise<void> => {
  if ("getReader" in body) {
    const reader = body.getReader();
    try {
      while (!(await reader.read()).done) {
        // Drain the stream so missing local files surface as read errors.
      }
    } finally {
      reader.releaseLock();
    }
    return;
  }

  for await (const _chunk of body) {
    // Drain the stream so missing local files surface as read errors.
  }
};

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
